### ISSUE TITLE
pyjaco installation

### ISSUE THREAD

**Issue by ghost** [chrivers/pyjaco#76]
When using the zip file from the githup site the installation fails with

Traceback (most recent call last):
  File "pyjaco/setup.py", line 8, in <module>
    version = get_version()
  File "/home/silentrunner/python/pyjaco/_version.py", line 46, in get_version
    raise ValueError('Could not determine version.')

this happens for both installing "standard" way or via virtualenv
pip install pyjaco
or 
python setup.py install

when cloning from github site installation works fine standard and virtualenv

testet with ubuntu 12.04

**Comment by derpasaurs** [comment]
change version = get_version() to version = "1.0.0",
